services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network

  # Express Backend Service
  server:
    build:
      context: ./server
    container_name: blogify-server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mern-network

  # React Frontend Service
  client:
    build:
      context: ./client
    container_name: blogify-client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - mern-network

volumes:
  mongodb_data:

networks:
  mern-network:
    driver: bridge
